### ISSUE TITLE
Erasing the outer walls crashes the simulator

### ISSUE THREAD

**Issue by MartinKist** [johnBuffer/AntSimulator#16]
Pretty much what the title says :)

Idk why i had so much fun dropping some food and building some obstacles and seeing these little virtual ants building an [ameisenstraße](https://de.wikipedia.org/wiki/Ameisenstra%C3%9Fe) (looks to me like there is no term for this phenomenon in english). 
Nice work 👍

**Comment by johnBuffer** [comment]
Thank you for this!
It's because I didn't implement any checks at the map's boundaries so it segfaults when trying to sample markers from outside the world. I was relying on walls to prevent this from happening but forgot that they can be removed :D 
Will add a fix for this.

**Comment by johnBuffer** [comment]
Fixed in master
