### ISSUE TITLE
Placing food and blocks

### ISSUE THREAD

**Issue by TheMrBlackLord** [johnBuffer/AntSimulator#24]
Hey! Is it possible to put food and walls in blocks at once (like some templates), instead of 1 point? Maybe it can be done programmatically?

**Comment by W-A-James** [comment]
@TheMrBlackLord  From looking at the code (lines 47-58) in main.cpp, it seems like you can upload a bitmap file that describes a layout for the food and walls.
You can use green pixels for food and red pixels for wall blocks

**Comment by johnBuffer** [comment]
Indeed, should add something about this in the readme.

**Comment by johnBuffer** [comment]
This will be directly address by the creation of the editor
