### ISSUE TITLE
Install instructions for not experienced people

### ISSUE THREAD

**Issue by Spartano** [johnBuffer/AntSimulator#4]
Hello,

i just saw you're video on youtube and wanted to make my son play with you're animation.

Do you think it is hard  if i ask you to make a more detailed instructions  file ?

Or maybe  a guide on how to put it online so i can share to others you're work.

Thank you.

**Comment by johnBuffer** [comment]
Hi,
If you are on Windows, you can try this link https://github.com/johnBuffer/AntSimulator/releases/download/v1.2/AntsSimulator.zip

**Comment by charanreigns** [comment]
What about Linux(Arch), I really wanna try THESE

**Comment by johnBuffer** [comment]
For arch you will need to install SFML with pacman (https://archlinux.org/packages/community/x86_64/sfml/) and build the project with cmake. Are you familiar with this process ?

**Comment by locxeu** [comment]
That relly cool bro. Great work!!!

**Comment by tnoktkm** [comment]
It`s so cool! I`m excited! Now I can study for you project programming own project in cpp :)

**Comment by gururani-abhishek** [comment]
> For arch you will need to install SFML with pacman (https://archlinux.org/packages/community/x86_64/sfml/) and build the project with cmake. Are you familiar with this process ?

No, can you please help me with it. I'm using ubuntu.

**Comment by charanreigns** [comment]
> For arch you will need to install SFML with pacman (https://archlinux.org/packages/community/x86_64/sfml/) and build the project with cmake. Are you familiar with this process ?

Nope. But I really wanna try.....can you explain it....

**Comment by johnBuffer** [comment]
I will add an installation guide soon

**Comment by charanreigns** [comment]
Thank you very much. @johnBuffer

**Comment by johnBuffer** [comment]
Just added more detailed instructions in the readme

**Comment by charanreigns** [comment]
@johnBuffer 

**Somtin gone wrong.......**

> [chitti@Thor build]$ make
Scanning dependencies of target AntSimulator
[ 25%] Building CXX object CMakeFiles/AntSimulator.dir/src/display_manager.cpp.o
In file included from /home/chitti/Documents/AntSimulator-master/include/marker.hpp:2,
                 from /home/chitti/Documents/AntSimulator-master/include/markers_grid.hpp:4,
                 from /home/chitti/Documents/AntSimulator-master/include/world.hpp:6,
                 from /home/chitti/Documents/AntSimulator-master/include/display_manager.hpp:4,
                 from /home/chitti/Documents/AntSimulator-master/src/display_manager.cpp:1:
/home/chitti/Documents/AntSimulator-master/include/config.hpp: In static member function ‘static void DefaultConf<T>::loadTextures()’:
/home/chitti/Documents/AntSimulator-master/include/config.hpp:25:3: error: ‘Conf’ has not been declared
   25 |   Conf::ANT_TEXTURE = std::make_shared<sf::Texture>();
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:26:3: error: ‘Conf’ has not been declared
   26 |   Conf::ANT_TEXTURE->loadFromFile("res/ant_2.png");
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:27:3: error: ‘Conf’ has not been declared
   27 |   Conf::ANT_TEXTURE->setSmooth(true);
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:29:3: error: ‘Conf’ has not been declared
   29 |   Conf::MARKER_TEXTURE = std::make_shared<sf::Texture>();
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:30:3: error: ‘Conf’ has not been declared
   30 |   Conf::MARKER_TEXTURE->loadFromFile("res/marker.png");
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:31:3: error: ‘Conf’ has not been declared
   31 |   Conf::MARKER_TEXTURE->setSmooth(true);
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp: In static member function ‘static void DefaultConf<T>::freeTextures()’:
/home/chitti/Documents/AntSimulator-master/include/config.hpp:36:3: error: ‘Conf’ has not been declared
   36 |   Conf::ANT_TEXTURE = nullptr;
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:37:3: error: ‘Conf’ has not been declared
   37 |   Conf::MARKER_TEXTURE = nullptr;
      |   ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp: At global scope:
/home/chitti/Documents/AntSimulator-master/include/config.hpp:43:17: error: specializing member ‘DefaultConf<>::ANT_COLOR’ requires ‘template<>’ syntax
   43 | const sf::Color Conf::ANT_COLOR = sf::Color(255, 73, 68);
      |                 ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:44:17: error: specializing member ‘DefaultConf<>::FOOD_COLOR’ requires ‘template<>’ syntax
   44 | const sf::Color Conf::FOOD_COLOR = sf::Color(66, 153, 66);
      |                 ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:45:17: error: specializing member ‘DefaultConf<>::TO_FOOD_COLOR’ requires ‘template<>’ syntax
   45 | const sf::Color Conf::TO_FOOD_COLOR = sf::Color(0, 255, 0);
      |                 ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:46:17: error: specializing member ‘DefaultConf<>::TO_HOME_COLOR’ requires ‘template<>’ syntax
   46 | const sf::Color Conf::TO_HOME_COLOR = sf::Color(255, 0, 0);
      |                 ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:47:17: error: specializing member ‘DefaultConf<>::COLONY_COLOR’ requires ‘template<>’ syntax
   47 | const sf::Color Conf::COLONY_COLOR = Conf::ANT_COLOR;
      |                 ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:48:10: error: specializing member ‘DefaultConf<>::WIN_WIDTH’ requires ‘template<>’ syntax
   48 | uint32_t Conf::WIN_WIDTH = 1920;
      |          ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:49:10: error: specializing member ‘DefaultConf<>::WIN_HEIGHT’ requires ‘template<>’ syntax
   49 | uint32_t Conf::WIN_HEIGHT = 1080;
      |          ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:50:10: error: specializing member ‘DefaultConf<>::ANTS_COUNT’ requires ‘template<>’ syntax
   50 | uint32_t Conf::ANTS_COUNT = 1024;
      |          ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:51:7: error: specializing member ‘DefaultConf<>::COLONY_SIZE’ requires ‘template<>’ syntax
   51 | float Conf::COLONY_SIZE = 20.0f;
      |       ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:52:14: error: specializing member ‘DefaultConf<>::COLONY_POSITION’ requires ‘template<>’ syntax
   52 | sf::Vector2f Conf::COLONY_POSITION = sf::Vector2f(Conf::WIN_WIDTH * 0.5f, Conf::WIN_HEIGHT * 0.5f);
      |              ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:55:30: error: specializing member ‘DefaultConf<>::ANT_TEXTURE’ requires ‘template<>’ syntax
   55 | std::shared_ptr<sf::Texture> Conf::ANT_TEXTURE;
      |                              ^~~~
/home/chitti/Documents/AntSimulator-master/include/config.hpp:56:30: error: specializing member ‘DefaultConf<>::MARKER_TEXTURE’ requires ‘template<>’ syntax
   56 | std::shared_ptr<sf::Texture> Conf::MARKER_TEXTURE;
      |                              ^~~~
make[2]: *** [CMakeFiles/AntSimulator.dir/build.make:82: CMakeFiles/AntSimulator.dir/src/display_manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/AntSimulator.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
[chitti@Thor build]$

**Comment by johnBuffer** [comment]
Will look into this, g++ and msvc don't behave the same regarding this.

**Comment by johnBuffer** [comment]
Should be better now
