### ISSUE TITLE
Crash in grid.hpp - vector subscript is out of range

### ISSUE THREAD

**Issue by StevenJAckerman** [johnBuffer/AntSimulator#41]
Running latest release, conf.txt file attached, using release map.png

[conf.txt](https://github.com/johnBuffer/AntSimulator/files/6989029/conf.txt)

![AntSimulator Crash call stack](https://user-images.githubusercontent.com/6642254/129495510-340b515e-f6f6-47f3-bc42-45ab74add9a5.png)

Cells vector subscript is out of range in this function:

	const T& getCst(sf::Vector2i cell_coord) const
	{
		return cells[getIndexFromCoords(cell_coord)];
	}

cell_coord.x = 207, cell_coord.y = 270, cells.size = 129600

In the called function, width = 480:

	uint64_t getIndexFromCoords(const sf::Vector2i& cell_coords) const
	{
		return cell_coords.x + cell_coords.y * width;
	}

So this returns 207 + (270 * 480) = 129807   which is out of range.

**Comment by johnBuffer** [comment]
Thanks, I did push a fix, it should be find now
