### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by Haxov** [johnBuffer/AntSimulator#42]
Hello, apologies for not building this on Linux but I currently don't have a proper setup for it. However when building in Windows, and after setting it up in CMake with SFML installed, I cannot build it fully in vs19. It says the "ALL_BUILD" folder does not exist and when trying to just run the application it crashes immediately. After debugging it, I come up with the error code 0xc0000005 which is an access violation even when ran as admin. I cant tell if it just isn't building the full game or if the directory might be messed up. If it were the former I would assume its known already but I just wanted to play around with some ants.

**Comment by Haxov** [comment]
If you need and files just let me know but other than the error code and the pop up that "ALL_BUILD" does not exist there isn't much else.

**Comment by abdulaziz40460** [comment]
I get the same pop up. did you know how to solve it?
![ERROR](https://user-images.githubusercontent.com/93984986/140918500-c0dbfcd5-a645-4c4e-b882-c1ec3a7969f1.jpg)

**Comment by johnBuffer** [comment]
Hello,

This is because the ALL_BUILD target is not runnable, you have to set AntsSimulator as the startup project in the solution explorer

**Comment by abdulaziz40460** [comment]
في ثلاثاء، ٩ نوفمبر، ٢٠٢١ في ٣:٠٩ م، كتب Jean Tampon <
***@***.***>:

**Comment by johnBuffer** [comment]
Perfect, I close this :)
