### ISSUE TITLE
Can't figure out controls on latest 3.1

### ISSUE THREAD

**Issue by TheFern2** [johnBuffer/AntSimulator#44]
I had played this on early versions where there was like an explosion from the center and ants scattered, was around march or april so whatever that version was current at the time. And I was able to play with the controls on readme, put food, place walls, etc. 

Version 3.1, simulation plays red vs blue, but I am not able to interact at all other than pause, is this a bug or is the game now entirely automated?

**Comment by TheFern2** [comment]
Bump 👀

**Comment by johnBuffer** [comment]
Hi, sorry for my late response. Currently there are no possible controls. I am however creating a new version with a lot more possibilities :)

**Comment by TheFern2** [comment]
@johnBuffer No worries, thanks for the response.
