### ISSUE TITLE
The GUI Doesn't Work When Maximizing The Window

### ISSUE THREAD

**Issue by Ker-Verse** [johnBuffer/AntSimulator#47]
It works fine in minimized mode but after maximizing the gui controls don't work just the camera controls

**Comment by johnBuffer** [comment]
Thank you for the report. I will patch this. A workaround if you want bigger window is to edit the conf.txt file (which is next to the executable) with bigger window size (the two first lines)

**Comment by johnBuffer** [comment]
This has been fixed on main branch.

**Comment by AAckerlund** [comment]
I just downloaded the 4.0 release and this still seems to be an issue. It looks like all button hit boxes are not scaling with the window if you adjust the size. They all stay at the default locations.

**Comment by johnBuffer** [comment]
It is not released yet, the patch just has been pushed on the main branch

**Comment by johnBuffer** [comment]
I just published the version 4.1 based on  master that fixes this issue. Don't hesitate to reopen if you still encounter this issue.
