### ISSUE TITLE
Scaling for the editor GUI?

### ISSUE THREAD

**Issue by victormihalache** [johnBuffer/AntSimulator#49]
I have a MacBook Air 13.3" (2560 x 1600 @ 227ppi) and it is kinda unusable:

<img width="1680" alt="Screenshot 2021-12-11 at 08 38 08" src="https://user-images.githubusercontent.com/82441538/145668685-8d7933bd-1fdd-43d2-8ba3-1444540982f7.png">

How can I change the scaling (within the code if there's currently no other solution)?

**Comment by johnBuffer** [comment]
Hi, I am working on it since I also have a MacBook with high dpi

**Comment by ericl16384** [comment]
Please also consider smaller screen sizes. Mine is 1366 x 768 and does not show the full menu.
![image](https://user-images.githubusercontent.com/45101992/146305108-e2afc976-65d4-4eee-8064-5f0a3962baa9.png)

**Comment by johnBuffer** [comment]
I am close to push a patch on main. It will add a scaling parameter in the configuration file (conf.txt) to scale the UI

**Comment by johnBuffer** [comment]
I just published the version 4.1 based on  master that includes a new line in the conf file to set the GUI scaling. Don't hesitate to reopen if you experience issues.
